### ISSUE TITLE
High ram usage and pixelated output

### ISSUE THREAD

**Issue by domingoO-jones** [aigagror/style-transfer-quality#5]

**Comment by domingoO-jones** [comment]
Hi,

Thanks for sharing this great work! I have noticed two things when using this implementation.
It seems that the implementation needs a lot of RAM to operate. I have a GPU with 4gb of RAM and can only produce pictures with resolution of 224x224 with other implementations, like Gatys, I can easily produce pictures with 512x512 up to 1024x1024. Do you know why this is the case?

Yesterday I tried to produce a picture with 1024x1024 on my cpu and the outcome is quite pixelated:
![gen](https://user-images.githubusercontent.com/68645053/91942319-06029380-ecfb-11ea-89bc-75941511dea8.png)

![2020-09-02 085532](https://user-images.githubusercontent.com/68645053/91942360-161a7300-ecfb-11ea-9eee-ded17be20cc3.png)

For comparison this is the picture I get from Gatys implementation computed on gpu:
![lion_cloudstone jpg](https://user-images.githubusercontent.com/68645053/91942387-229ecb80-ecfb-11ea-8d83-8258d57ebb61.png)

![ausschnitt](https://user-images.githubusercontent.com/68645053/91942839-def89180-ecfb-11ea-896b-b757df42dd73.png)

Is this because I used the cpu for optimization or does this come from somewhere else?

Best regards

**Comment by aigagror** [comment]
Hi domingoO,

This issue of high RAM usage is probably because the batch size to the discriminators is much larger. Note that the batch size for the discriminator is equal to the number of features in the corresponding layer. With higher resolution, we have more features. An easy way to fix this is to mini-batch the features that are fed into the discriminator.

If someone would like to make a PR for this, I would happily review it. Due to my time constraints, it may take sometime for me to add this feature myself

**Comment by C00reNUT** [comment]
Hello, @aigagror thank you for this algorithm and implementation. The results are very nice and the output quality is clearily superior to other methods.

Is there any chance you could implement the batch size you mentioned? Otherwise the Wasserstein distance with multiple layers is restricted to very small image inputs. Even with high GPU RAMs.

**Comment by aigagror** [comment]
This issue has been resolved with the `samples` argument. The `samples` argument dictates the mini-batch size to sample the number of features from each layer in the style transfer.
